[workspace]
members = ["banana_core", "banana_train"]

[workspace.dependencies]
ed25519 = "2.2.3"
tokio = { version = "1.44.2", features = ["full"] }
rusqlite = { version = "0.35.0", features = ["bundled"] }
