[package]
name = "banana_messenger_core"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
p384 = "0.13.1"
ed25519 = { workspace = true }
tokio = { workspace = true }
rusqlite = { workspace = true }
