[package]
name = "banana_train"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
rusqlite = { workspace = true }
ron = { workspace = true }
netwrk = { path = "../netwrk" }
