name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build debug
      run: cargo build
    - name: Test debug
      run: cargo test
    - name: Build release
      run: cargo build -r --verbose
    - name: Run tests release
      run: cargo test -r --verbose
